/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVoiceRouteImport } from './routes/app.voice'
import { Route as AppRoomsRouteImport } from './routes/app.rooms'
import { Route as AppQuizRouteImport } from './routes/app.quiz'
import { Route as AppPodcastRouteImport } from './routes/app.podcast'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppDrawRouteImport } from './routes/app.draw'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppBattleRouteImport } from './routes/app.battle'
import { Route as AppBadgesRouteImport } from './routes/app.badges'
import { Route as ApiVoiceRouteImport } from './routes/api/voice'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppRoomRoomIdRouteImport } from './routes/app.room.$roomId'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizRoute = AppQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AppRoute,
} as any)
const AppPodcastRoute = AppPodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppDrawRoute = AppDrawRouteImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBattleRoute = AppBattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => AppRoute,
} as any)
const AppBadgesRoute = AppBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AppRoute,
} as any)
const ApiVoiceRoute = ApiVoiceRouteImport.update({
  id: '/api/voice',
  path: '/api/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoomRoomIdRoute = AppRoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/voice': typeof ApiVoiceRoute
  '/app/badges': typeof AppBadgesRoute
  '/app/battle': typeof AppBattleRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/draw': typeof AppDrawRoute
  '/app/notes': typeof AppNotesRoute
  '/app/podcast': typeof AppPodcastRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/rooms': typeof AppRoomsRoute
  '/app/voice': typeof AppVoiceRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/app/room/$roomId': typeof AppRoomRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/voice': typeof ApiVoiceRoute
  '/app/badges': typeof AppBadgesRoute
  '/app/battle': typeof AppBattleRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/draw': typeof AppDrawRoute
  '/app/notes': typeof AppNotesRoute
  '/app/podcast': typeof AppPodcastRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/rooms': typeof AppRoomsRoute
  '/app/voice': typeof AppVoiceRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/app/room/$roomId': typeof AppRoomRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/voice': typeof ApiVoiceRoute
  '/app/badges': typeof AppBadgesRoute
  '/app/battle': typeof AppBattleRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/draw': typeof AppDrawRoute
  '/app/notes': typeof AppNotesRoute
  '/app/podcast': typeof AppPodcastRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/rooms': typeof AppRoomsRoute
  '/app/voice': typeof AppVoiceRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/app/room/$roomId': typeof AppRoomRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/docs'
    | '/api/chat'
    | '/api/voice'
    | '/app/badges'
    | '/app/battle'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/draw'
    | '/app/notes'
    | '/app/podcast'
    | '/app/quiz'
    | '/app/rooms'
    | '/app/voice'
    | '/api/admin/stats'
    | '/app/room/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/docs'
    | '/api/chat'
    | '/api/voice'
    | '/app/badges'
    | '/app/battle'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/draw'
    | '/app/notes'
    | '/app/podcast'
    | '/app/quiz'
    | '/app/rooms'
    | '/app/voice'
    | '/api/admin/stats'
    | '/app/room/$roomId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/docs'
    | '/api/chat'
    | '/api/voice'
    | '/app/badges'
    | '/app/battle'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/draw'
    | '/app/notes'
    | '/app/podcast'
    | '/app/quiz'
    | '/app/rooms'
    | '/app/voice'
    | '/api/admin/stats'
    | '/app/room/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiVoiceRoute: typeof ApiVoiceRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/voice': {
      id: '/app/voice'
      path: '/voice'
      fullPath: '/app/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rooms': {
      id: '/app/rooms'
      path: '/rooms'
      fullPath: '/app/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quiz': {
      id: '/app/quiz'
      path: '/quiz'
      fullPath: '/app/quiz'
      preLoaderRoute: typeof AppQuizRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/podcast': {
      id: '/app/podcast'
      path: '/podcast'
      fullPath: '/app/podcast'
      preLoaderRoute: typeof AppPodcastRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/draw': {
      id: '/app/draw'
      path: '/draw'
      fullPath: '/app/draw'
      preLoaderRoute: typeof AppDrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/battle': {
      id: '/app/battle'
      path: '/battle'
      fullPath: '/app/battle'
      preLoaderRoute: typeof AppBattleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/badges': {
      id: '/app/badges'
      path: '/badges'
      fullPath: '/app/badges'
      preLoaderRoute: typeof AppBadgesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/voice': {
      id: '/api/voice'
      path: '/api/voice'
      fullPath: '/api/voice'
      preLoaderRoute: typeof ApiVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/room/$roomId': {
      id: '/app/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/app/room/$roomId'
      preLoaderRoute: typeof AppRoomRoomIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBadgesRoute: typeof AppBadgesRoute
  AppBattleRoute: typeof AppBattleRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDrawRoute: typeof AppDrawRoute
  AppNotesRoute: typeof AppNotesRoute
  AppPodcastRoute: typeof AppPodcastRoute
  AppQuizRoute: typeof AppQuizRoute
  AppRoomsRoute: typeof AppRoomsRoute
  AppVoiceRoute: typeof AppVoiceRoute
  AppRoomRoomIdRoute: typeof AppRoomRoomIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBadgesRoute: AppBadgesRoute,
  AppBattleRoute: AppBattleRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDrawRoute: AppDrawRoute,
  AppNotesRoute: AppNotesRoute,
  AppPodcastRoute: AppPodcastRoute,
  AppQuizRoute: AppQuizRoute,
  AppRoomsRoute: AppRoomsRoute,
  AppVoiceRoute: AppVoiceRoute,
  AppRoomRoomIdRoute: AppRoomRoomIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiVoiceRoute: ApiVoiceRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
